BookStoreWeb/Models/BooksListViewModel.cs
using BookStoreDomainModel.Entities;
using System.Collections.Generic;

namespace BookStoreWeb.Models
{
    public class BooksListViewModel
    {
        public IEnumerable<Book> Books { get; set; }
        public PageInfo PageInfo { get; set; }
        public string Category { get; set; }
    }
}

BookStoreWeb/Models/CartViewModel.cs
using BookStoreDomainModel.Entities;

namespace BookStoreWeb.Models
{
    public class CartViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUri { get; set; }
    }
}

BookStoreWeb/Models/PageInfo.cs
using System;

namespace BookStoreWeb.Models
{
    public class PageInfo
    {
        public int ItemsCount { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }
        public int PagesCount
        {
            get
            {
                return (int)Math.Ceiling((decimal)ItemsCount / ItemsPerPage);
            }
        }
    }
}

BookStoreWeb/Controllers/CartController.cs
using BookStoreDomainModel.Abstract;
using System.Web.Mvc;
using System.Linq;
using BookStoreDomainModel.Entities;
using BookStoreWeb.Models;

namespace BookStoreWeb.Controllers
{
    public class CartController : Controller
    {
        private IBookRepository bookRepository = null;
        private IOrderProcess orderProcess = null;

        // Get book repository and orderProcess from di(Dependency Injection)
        public CartController(IBookRepository bookRepository, IOrderProcess orderProcess)
        {
            this.bookRepository = bookRepository;
            this.orderProcess = orderProcess;
        }

        // Show cart
        public ViewResult Index(Cart cart, string returnUri)
        {
            return View(new CartViewModel()
            {
                Cart = cart,
                ReturnUri = returnUri
            });
        }

        public RedirectToRouteResult AddItemToCart(Cart cart, int id, string returnUri)
        {
            Book book = bookRepository.Books.FirstOrDefault(item => item.Id == id);
            if(book != null)
            {
                cart.AddItem(book, 1);
            }
            return RedirectToAction("Index", new {returnUri });
        }

        public RedirectToRouteResult RemoveItemFromCart(Cart cart, int bookId, string returnUri)
        {
            Book book = bookRepository.Books.Where(item => item.Id == bookId).FirstOrDefault();
            if(book != null)
            {
                cart.RemoveItem(book);
            }
            return RedirectToAction("Index", new {returnUri });
        }

        // Link for a widget to be able to look into the cart
        public PartialViewResult CartSummary(Cart cart)
        {
            return PartialView(cart);
        }

        // Show Order View
        public ViewResult MakeOrder(Cart cart)
        {
            return View(new Order());
        }

        // Create an order
        [HttpPost]
        public ViewResult Checkout(Cart cart, Order order)
        {
            if(cart.Goods.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty.");
            }

            if(ModelState.IsValid)
            {
                orderProcess.Order(cart, order);
                cart.ClearItems();
                return View("ShoppingCompleted");
            }
            else
            {
                return View("MakeOrder", order);
            }
        }
    }
}

BookStoreWeb/Controllers/HomeController.cs
using System.Linq;
using BookStoreWeb.Models;
using System.Web.Mvc;
using BookStoreDomainModel.Abstract;

namespace BookStoreWeb.Controllers
{
    public class HomeController : Controller
    {
        private IBookRepository bookRepository = null;
        private int pageSize = 4;

        // Get book using di
        public HomeController(IBookRepository bookRepository)
        {
            this.bookRepository = bookRepository;
        }

        // Show a list of books by category for a specified page
        public ViewResult Index(string category, int page = 1)
        {
            BooksListViewModel model = new BooksListViewModel()
            {
                Books = bookRepository.Books.Where(book => category == null || book.Category  == category)
                .OrderBy(book => book.Id).Skip((page - 1) * pageSize).Take(pageSize),
                PageInfo = new PageInfo()
                {
                    CurrentPage = page,
                    ItemsCount = category == null ? bookRepository.Books.Count(): bookRepository.Books.Where(x => x.Category == category).Count(),
                    ItemsPerPage = pageSize
                },
                Category = category
            };
            return View(model);
        }
    }
}

BookStoreWeb/Controllers/MenuController.cs
using System.Web.Mvc;
using BookStoreDomainModel.Abstract;
using System.Collections.Generic;
using System.Linq;

namespace BookStoreWeb.Controllers
{
    public class MenuController : Controller
    {
        private IBookRepository bookRepository = null;

        // Get book repository from di
        public MenuController(IBookRepository bookRepository)
        {
            this.bookRepository = bookRepository;
        }

        // Create a side menu to allow users' category selection
        public PartialViewResult ShowSideMenu(string category)
        {
            ViewBag.SelectedCategory = category;
            IEnumerable<string> categories = bookRepository.Books.Select(book => book.Category).Distinct().OrderBy(book => book);
            return PartialView("SideMenu", categories);
        }
    }
}

BookStoreWeb/Views/Cart/CartSummary.cshtml
@model BookStoreDomainModel.Entities.Cart

<div class="navbar-right btn-sm">
        @Html.ActionLink("Order", "Index", "Cart", new {returnUri = Request.Url.PathAndQuery }, new {@class = "btn btn-primary" })
</div>
<div class="navbar-text navbar-right">
    <b>Your cart:</b>
    @Model.Goods.Sum(item => item.Quantity) books,
    @Model.CalculateTotalPrice().ToString("#USD")
</div>

BookStoreWeb/Views/Cart/Index.cshtml
@model BookStoreWeb.Models.CartViewModel

@{
    ViewBag.Title = "Your cart:";
}

<h2>This is your cart</h2>
<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th class="text-center text-white">Quantity</th>
                <th class="text-center">Book</th>
                <th class="text-center">Price</th>
                <th class="text-center">Total price</th>
                <th class="text-center">Remove item</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Cart.Goods)
            {
            <tr>
                <td class="text-center">@item.Quantity</td>
                <td class="text-center">@item.Book.Name</td>
                <td class="text-center">@item.Book.Price.ToString("#USD")</td>
                <td class="text-center">@((item.Quantity * item.Book.Price).ToString("#USD"))</td>
                <td class="text-center">
                @using (Html.BeginForm("RemoveItemFromCart", "Cart"))
                {
                    @Html.Hidden("BookId", item.Book.Id)
                    @Html.HiddenFor(x => x.ReturnUri)
                    <input class="btn btn-sm btn-warning" type="submit" value="Remove">
                }
                </td >
            </tr>
             }
        </tbody>
        <tfoot>
            <tr class="success">
                <td></td>
                <td></td>
                <td class="text-center">Total:</td>
                <td class="text-center">@Model.Cart.CalculateTotalPrice().ToString("#USD")</td>
                <td></td>
            </tr>
        </tfoot>
    </table>
</div>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUri">Continue shopping</a>
    @Html.ActionLink("Make order", "MakeOrder", null, new {@class = "btn btn-primary" })
</div>

BookStoreWeb/Views/Cart/MakeOrder.cshtml
@model BookStoreDomainModel.Entities.Order

@{
    ViewBag.Title = "BookStore: order form";
}

<h2>Make an order now</h2>
<p>Please enter your contact data and you'll get goods!</p>

@using (Html.BeginForm("Checkout", "Cart"))
{
    @Html.ValidationSummary()
    <h3>Data</h3>
    <div class="form-group">
        <label>Your name:</label>
        @Html.TextBoxFor(order => order.Name, new { @class = "form-control" })
    </div>

    <div class="form-group">
        <label>Your street address:</label>
        @Html.TextBoxFor(order => order.Street, new { @class = "form-control" })
    </div>

    <div class="form-group">
        <label>Your home address:</label>
        @Html.TextBoxFor(order => order.HomeNumber, new { @class = "form-control" })
    </div>

    <div class="form-group">
        <label>Your city:</label>
        @Html.TextBoxFor(order => order.City, new { @class = "form-control" })
    </div>

    <div class="form-group">
        <label>Your country:</label>
        @Html.TextBoxFor(order => order.Country, new { @class = "form-control" })
    </div>

    <div class="text-center">
        <input class="btn btn-primary" type="submit" value="Process order"/> 
    </div>
}

BookStoreWeb/Views/Cart/ShoppingCompleted.cshtml
@{
    ViewBag.Title = "Shopping was completed successfully!";
}

<h2>Thanks!</h2>
<p>Thanks for your order. Choose the best and get it!</p>

BookStoreWeb/Views/Home/Index.cshtml
@using BookStoreWeb.Models
@model BooksListViewModel

@{
    ViewBag.Title = "Books";
}

@foreach (var book in @Model.Books)
{
    @Html.Partial("PartialBooksView", book)
}

    <div class="btn-group pull-right">
        @Html.CreatePages(Model.PageInfo, x => Url.Action("Index", new {page = x, category = Model.Category }))
    </div>

BookStoreWeb/Views/Menu/SideMenu.cshtml
@model IEnumerable<string>

@Html.ActionLink("Home", "Index", "Home", null, new {@class = "btn btn-block btn-default btn-lg" })

@foreach (string link in @Model)
{
    @Html.RouteLink(link, new
    {
        controller = "Home",
        action = "Index",
        category = link,
        page = 1
    },
    new
    {
        @class = "btn btn-block btn-default btn-lg"
        + (link == ViewBag.SelectedCategory ? " btn-primary" : "")
    })
}

BookStoreWeb/Views/Shared/PartialBooksView.cshtml
@model BookStoreDomainModel.Entities.Book

<div class="well">
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">@Model.Price.ToString("# Dollars")</span>
    </h3>
    @using (Html.BeginForm("AddItemToCart", "Cart"))
    {
        <div class="pull-right">
            @Html.HiddenFor(x => x.Id)
            @Html.Hidden("returnUri", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Add to Cart">
        </div>
    }

    <span class="lead">@Model.Description</span>
</div>

BookStoreWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyle.css" rel="stylesheet"/>
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">BookStore - a store of the best books</a>
        @Html.Action("CartSummary", "Cart")
    </div>
    <div class="row panel" style="width: 100%;">
        <div id="categories" class="col-xs-3">
            @Html.Action("ShowSideMenu", "Menu")
        </div>
        <div class="col-xs-8">
            @RenderBody()
        </div>
    </div>
</body>
</html>